<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entities\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'appends' => [parent::class, 'appends', null],
        "\0".'*'."\0".'attributeCastCache' => [parent::class, 'attributeCastCache', null],
        "\0".'*'."\0".'attributes' => [parent::class, 'attributes', null],
        "\0".'*'."\0".'authPasswordName' => [parent::class, 'authPasswordName', null],
        "\0".'*'."\0".'casts' => [parent::class, 'casts', null],
        "\0".'*'."\0".'changes' => [parent::class, 'changes', null],
        "\0".'*'."\0".'classCastCache' => [parent::class, 'classCastCache', null],
        "\0".'*'."\0".'connection' => [parent::class, 'connection', null],
        "\0".'*'."\0".'dateFormat' => [parent::class, 'dateFormat', null],
        "\0".'*'."\0".'dispatchesEvents' => [parent::class, 'dispatchesEvents', null],
        "\0".'*'."\0".'escapeWhenCastingToString' => [parent::class, 'escapeWhenCastingToString', null],
        "\0".'*'."\0".'fillable' => [parent::class, 'fillable', null],
        "\0".'*'."\0".'guarded' => [parent::class, 'guarded', null],
        "\0".'*'."\0".'hidden' => [parent::class, 'hidden', null],
        "\0".'*'."\0".'keyType' => [parent::class, 'keyType', null],
        "\0".'*'."\0".'observables' => [parent::class, 'observables', null],
        "\0".'*'."\0".'original' => [parent::class, 'original', null],
        "\0".'*'."\0".'perPage' => [parent::class, 'perPage', null],
        "\0".'*'."\0".'primaryKey' => [parent::class, 'primaryKey', null],
        "\0".'*'."\0".'relations' => [parent::class, 'relations', null],
        "\0".'*'."\0".'rememberTokenName' => [parent::class, 'rememberTokenName', null],
        "\0".'*'."\0".'table' => [parent::class, 'table', null],
        "\0".'*'."\0".'touches' => [parent::class, 'touches', null],
        "\0".'*'."\0".'visible' => [parent::class, 'visible', null],
        "\0".'*'."\0".'with' => [parent::class, 'with', null],
        "\0".'*'."\0".'withCount' => [parent::class, 'withCount', null],
        "\0".parent::class."\0".'articles' => [parent::class, 'articles', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        'appends' => [parent::class, 'appends', null],
        'articles' => [parent::class, 'articles', null],
        'attributeCastCache' => [parent::class, 'attributeCastCache', null],
        'attributes' => [parent::class, 'attributes', null],
        'authPasswordName' => [parent::class, 'authPasswordName', null],
        'casts' => [parent::class, 'casts', null],
        'changes' => [parent::class, 'changes', null],
        'classCastCache' => [parent::class, 'classCastCache', null],
        'connection' => [parent::class, 'connection', null],
        'dateFormat' => [parent::class, 'dateFormat', null],
        'dispatchesEvents' => [parent::class, 'dispatchesEvents', null],
        'email' => [parent::class, 'email', null],
        'escapeWhenCastingToString' => [parent::class, 'escapeWhenCastingToString', null],
        'exists' => [parent::class, 'exists', null],
        'fillable' => [parent::class, 'fillable', null],
        'guarded' => [parent::class, 'guarded', null],
        'hidden' => [parent::class, 'hidden', null],
        'id' => [parent::class, 'id', null],
        'incrementing' => [parent::class, 'incrementing', null],
        'keyType' => [parent::class, 'keyType', null],
        'name' => [parent::class, 'name', null],
        'observables' => [parent::class, 'observables', null],
        'original' => [parent::class, 'original', null],
        'password' => [parent::class, 'password', null],
        'perPage' => [parent::class, 'perPage', null],
        'preventsLazyLoading' => [parent::class, 'preventsLazyLoading', null],
        'primaryKey' => [parent::class, 'primaryKey', null],
        'relations' => [parent::class, 'relations', null],
        'rememberTokenName' => [parent::class, 'rememberTokenName', null],
        'table' => [parent::class, 'table', null],
        'timestamps' => [parent::class, 'timestamps', null],
        'touches' => [parent::class, 'touches', null],
        'usesUniqueIds' => [parent::class, 'usesUniqueIds', null],
        'visible' => [parent::class, 'visible', null],
        'wasRecentlyCreated' => [parent::class, 'wasRecentlyCreated', null],
        'with' => [parent::class, 'with', null],
        'withCount' => [parent::class, 'withCount', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        $data = [];

        foreach (parent::__sleep() as $name) {
            $value = $properties[$k = $name] ?? $properties[$k = "\0*\0$name"] ?? $properties[$k = "\0App\Entities\User\0$name"] ?? $k = null;

            if (null === $k) {
                trigger_error(sprintf('serialize(): "%s" returned as member variable from __sleep() but does not exist', $name), \E_USER_NOTICE);
            } else {
                $data[$k] = $value;
            }
        }

        return $data;
    }
}
